CREATE TABLE order_product
(
    quantity INTEGER NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL

);

CREATE TABLE orders
(
    id BIGINT generated by default as identity,
    date_created DATE,
    status VARCHAR(255)
);

CREATE TABLE product
(
    id BIGINT generated by default as identity,
    name VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255),
    price DOUBLE PRECISION
);
