---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/p.dmitriev/sausage-store/sausage-backend-report:latest
          name: backend-report
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: REPORT_PATH
              valueFrom: 
                configMapKeyRef:
                  name: backend-report-configmap
                  key: report_path

            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: backend-report
              containerPort: 8081
      imagePullSecrets:
        - name: docker-config-secret