---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJkZXBsb3llciIsInBhc3N3b3JkIjoianppODcxX0VfYXhiUlZ5WmNHOXQiLCJlbWFpbCI6ImRtaXRyaWV2cGE4NUB5YW5kZXgucnUiLCJhdXRoIjoiWkdWd2JHOTVaWEk2YW5wcE9EY3hYMFZmWVhoaVVsWjVXbU5IT1hRPSJ9fX0=
type: kubernetes.io/dockerconfigjson