stages:
  - build
variables:
  HELM_VERSION: 1.0.${CI_PIPELINE_ID}
build:
  stage: build
  image: alpine/k8s:1.25.4
  script:
    - sed  -i 's/0\.1\..*'/$HELM_VERSION'/g' ./momo-store-chart/Chart.yaml
    - helm package ./momo-store-chart
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_URL} --upload-file ./momo-store-${HELM_VERSION}.tgz
  rules:
    - changes:
      - momo-store-chart/**/*
  



