stages:
  - module-pipelines
helm:
  stage: module-pipelines
  trigger:
    include:
      - "/momo-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - momo-store-chart/**/*
terraform:
  stage: module-pipelines
  trigger:
    include:
      - "/terraform/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - terraform/**/*
argocd:
  stage: module-pipelines
  trigger:
    include:
      - "argocd.gitlab-ci.yml"
    strategy: depend
  when: manual
monitoring:
  stage: module-pipelines
  trigger:
    include:
      - "/monitoring/.gitlab-ci.yml"
    strategy: depend
  when: manual
  



