stages:
  - build
  - prepare
  - install
image:
    name: alpine/k8s:1.25.4
build:
  stage: build
  script:
    - helm package ./argo-cd-chart
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_INFRA_URL} --upload-file ./argo-cd-4.5.3-1.tgz
  rules:
    - changes:
      - argo-cd-chart/**/*
prepare-argocd:
  stage: prepare
  before_script:
  - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - /root/yandex-cloud/bin/yc config profile create deploy
  - /root/yandex-cloud/bin/yc config set token ${YC_TOKEN}
  - /root/yandex-cloud/bin/yc config set cloud-id ${YC_CLOUD_ID}
  - /root/yandex-cloud/bin/yc config set folder-id ${YC_FOLDER_ID}
  - /root/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --name ${K8S_CLUSTER_NAME} --external
  script:
    - cd terraform/files
    - kubectl apply -f acme-issuer.yaml
install-app:
  stage: install
  variables:
    argocd_app_name: momo-store
  before_script:
    - curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    - install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - /root/yandex-cloud/bin/yc config profile create deploy
    - /root/yandex-cloud/bin/yc config set token ${YC_TOKEN}
    - /root/yandex-cloud/bin/yc config set cloud-id ${YC_CLOUD_ID}
    - /root/yandex-cloud/bin/yc config set folder-id ${YC_FOLDER_ID}
    - /root/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --name ${K8S_CLUSTER_NAME} --external
  script:
    - export ARGO_PASS=$(kubectl --namespace argocd  get secret argocd-initial-admin-secret --output jsonpath="{.data.password}" | base64 -d)
    - argocd login ${ARGO_SERVER} --grpc-web --username ${ARGO_USER} --password ${ARGO_PASS}
    - argocd repo add  ${NEXUS_REPO_URL} --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS} --type helm --name momo-store
    - argocd app create momo-store --repo ${NEXUS_REPO_URL} --helm-chart momo-store --revision 1.0.x --dest-namespace default --dest-server https://kubernetes.default.svc
  when: manual