cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

variables:
   VERSION: 1.0.${CI_PIPELINE_ID}
   MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
   JAVA_OPTS: -XX:MaxRAMPercentage=90

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'
  - template: Security/Container-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - release
  - notify
  - deploy

build-backend-report:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables: 
    KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
  script:
    - > 
      mkdir -p /kaniko/.docker
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor 
        --context $CI_PROJECT_DIR/backend-report
        --build-arg VERSION=$VERSION
        --dockerfile $CI_PROJECT_DIR/backend-report/Dockerfile $KANIKO_CACHE_ARGS
        --destination $CI_REGISTRY_IMAGE/sausage-backend-report:$CI_COMMIT_SHA
  rules:
    - changes:
           - backend-report/*
  
spotbugs-sast:
  stage: test
  dependencies:
    - build-backend-report
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    SAST_EXCLUDED_ANALYZERS: "spotbugs"
  artifacts:
    reports:
      sast: gl-sast-report.json

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.m2/repository"
    GIT_DEPTH: "0"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /run tests/
    - changes:
           - backend-report/*
  script:
    - cd backend-report
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=$SONAR_BACKEND_REPORT_PROJECT_KEY
      -Dsonar.host.url=$SONARQUBE_URL
      -Dsonar.login=$SONAR_BACKEND_REPORT_TOKEN
      -Dsonar.projectName=$SONAR_BACKEND_REPORT_PROJECT_NAME
      -Dsonar.scm.provider=git
  allow_failure: true
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
container_scanning:
  stage: test
  variables:
    CS_IMAGE: $CI_REGISTRY_IMAGE/sausage-backend-report:$CI_COMMIT_SHA
    CS_REGISTRY_USER: $DOCKER_USER
    CS_REGISTRY_PASSWORD: ${DOCKER_TOKEN}
  artifacts:
    paths:
      - gl-container-scanning-report.json




upload-backend-report-latest:
  dependencies:
    - build-backend-report
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  stage: release
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/sausage-backend-report:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/sausage-backend-report:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/sausage-backend-report:latest
    - docker push $CI_REGISTRY_IMAGE/sausage-backend-report:latest


slack-notification-backend-report:
  stage: notify
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notify/
      changes:
      - backend/**/*
  variables:
    ARTIFACTS_PATH: com/yandex/practicum/devops/${CI_PROJECT_NAME}
    APP_NAME: backend
    EXTENDS: jar
  script:
      - curl -X POST -H "Content-type:application/json" --data "{'text':'Вышла новая версия ${APP_NAME} сосисочной — ${VERSION}. Скачать ${APP_NAME} можно по ссылке — ${NEXUS_REPO_URL}-${APP_NAME}/${ARTIFACTS_PATH}/${VERSION}/${CI_PROJECT_NAME}-${VERSION}.${EXTENDS}'}" ${SLACK_WEBHOOK}
  needs:
    - upload-backend-report-latest

deploy-backend-report:
  stage: deploy
  variables:
    VERSION: ${VERSION}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual
  trigger:
    project: 'p.dmitriev/infrastructure'
    branch: main
    strategy: depend