---
replicaCount: 1

labels:
  app.kubernetes.io/name: frontend
  app.kubernetes.io/instance: "momo-frontend"
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: helm
  helm.sh/chart: "momo-store-chart-0.1.0"
  meta.helm.sh/release-namespace: std-007-030
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: momo-store

  env: production

image:
  repository: gitlab.praktikum-services.ru:5050/p.dmitriev/momo-store/momo-frontend
  pullPolicy: Always
  tag: ""

imagePullSecrets: 
  - name: docker-config-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: momo-store.mangoit.me
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: momo-store-frontend
              port:
                number: 80
  tls:
    - 
      hosts:
        - momo-store.mangoit.me
      secretName: letsencrypt


resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
