---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLld4MVZpV25Od3JpY1VEckpYdnRHUGYwMg==
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJkZXBsb3llciIsInBhc3N3b3JkIjoidmt6SlV2TXNRX3Q0cnQ1d3hzUFEiLCJlbWFpbCI6ImRtaXRyaWV2cGE4NUB5YW5kZXgucnUiLCJhdXRoIjoiWkdWd2JHOTVaWEk2ZG10NlNsVjJUWE5SWDNRMGNuUTFkM2h6VUZFPSJ9fX0=
type: kubernetes.io/dockerconfigjson