replicaCount: 1

image:
  repository: gitlab.praktikum-services.ru:5050/p.dmitriev/sausage-store/sausage-backend-report
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: 
  - name: docker-config-secret

env:
  - name: REPORT_PATH
    value: '/app/reports/'

vault:
  tokenSecretName: 

service:
  type: ClusterIP
  port: 8081
resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1000m"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
