apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  10240;
    }

    http {
        #include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        proxy_cache_path /data/nginx/cache keys_zone=sscache:10m loader_threshold=300 loader_files=200 max_size=200m;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
        
    }
    #daemon off;
  default.conf: |
   
    server {

      listen 8080;
      proxy_cache sscache;
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend:8080;
      }
    }