replicaCount: 1

labels:
  app.kubernetes.io/name: backend
  app.kubernetes.io/instance: "momo-backend"
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: helm
  helm.sh/chart: "momo-store-chart-0.1.0"
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: momo-store
  meta.helm.sh/release-namespace: std-007-030
  env: production
image:
  repository: gitlab.praktikum-services.ru:5050/p.dmitriev/sausage-store/momo-backend
  pullPolicy: Always
  tag: ""

imagePullSecrets: 
  - name: docker-config-secret


service:
  type: ClusterIP
  port: 8081

autoscaling:
  enabled: false
resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
